#!/bin/sh

PASS_PHRASE=$1
OWNER_ADDRESS=$2
USER=forta


FORTA_CONFIG='# Auto generated by "forta init" - safe to modify
# The chainId is the chainId of the network that is analyzed (1=mainnet)
chainId: 1

# The scan settings are used to retrieve the transactions that are analyzed
scan:
  jsonRpc:
    url: https://rpc.ankr.com/eth

# The trace endpoint must support trace_block (such as alchemy)
trace:
  jsonRpc:
    url: https://eth-mainnet.g.alchemy.com/v2/SbwYv1dbQ2on7DN8nSAfOQXEBKw3-S2k

# The registry settings are used to discover and load agents
# registry:
#  jsonRpc:
#    url: https://polygon-rpc.com/
#  ipfs:
#    gatewayUrl: https://ipfs.forta.network
#    username: <set if needed>
#    password: <set if needed>

# The jsonRpcProxy settings are used make query requests (defaults to scan url)
# jsonRpcProxy:
#   jsonRpc:
#     url: <enter if different from scan value>

# The publish settings drive how alerts are sent
# publish:
#  ipfs:
#    apiUrl: https://ipfs.forta.network
#    username: <set if needed>
#    password: <set if needed>

# The log settings drive the log output of the scan node
# log:
#  level: info
#  maxLogSize: 50m
#  maxLogFiles: 10'

DAEMON_JSON='{
   "default-address-pools": [
        {
            "base":"172.17.0.0/12",
            "size":16
        },
        {
            "base":"192.168.0.0/16",
            "size":20
        },
        {
            "base":"10.99.0.0/16",
            "size":24
        }
    ]
}'

# Enable and start time sync service.
function time_sync(){
    systemctl enable systemd-timesyncd
    systemctl start systemd-timesyncd

    timedatectl status
}


# Install docker on centos7.
function install_docker(){
    yum remove docker \
        docker-client \
        docker-client-latest \
        docker-common \
        docker-latest \
        docker-latest-logrotate \
        docker-logrotate \
        docker-engine

    yum install -y yum-utils

    yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo

    yum install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

    echo "$DAEMON_JSON" > /etc/docker/daemon.json

    systemctl start docker
}


#Install forta on centos7.
function install_forta(){
    curl https://dist.forta.network/repositories/yum/Forta.repo -o /etc/yum.repos.d/Forta.repo -s

    yum install -y forta
}

# Create forta user and add it in docker group.
function create_user(){
    useradd -m forta
    usermod -aG docker $USER
}


# Initialize forta.
function forta_init(){
    su - $USER -c "forta init --passphrase=$PASS_PHRASE"
}


# Config forta.
function config_forta(){
    echo "$FORTA_CONFIG" > "/home/$USER/.forta/config.yml"
}

function start_forta(){
    echo "[Service]
Environment='FORTA_DIR=/home/$USER/.forta'
Environment='FORTA_PASSPHRASE=$PASS_PHRASE'" > /etc/systemd/system/forta.service.d/env.conf

    systemctl daemon-reload
    systemctl enable forta
    systemctl start forta
}


function forta_register(){
    su - $USER -c "forta register --owner-address=$OWNER_ADDRESS --passphrase=$PASS_PHRASE"
}

install_docker

install_forta

create_user

forta_init

config_forta